package logs

import (
	"errors"
	"fmt"
	"io/fs"
	"log"

	"github.com/gilperopiola/grpc-gateway-impl/app/core"
	"go.uber.org/zap"
)

func Step(step int) {
	log.Printf("%s\n", numbersToEmojis[step])
}

func SubstepOK(name, emoji string) {
	log.Printf("\t %s %s OK\n", emoji, name)
}

func EnvVars() {
	log.Println(" \tüéà APP = " + core.G.AppName + " " + core.G.Version)
	log.Println(" \tüåê ENV = " + core.G.Env)
	if core.G.TLSEnabled {
		log.Println(" \t‚úÖ TLS = on")
	} else {
		log.Println(" \t‚ö†Ô∏è  TLS = off")
	}
}

var numbersToEmojis = map[int]string{
	0:  "0Ô∏è‚É£",
	1:  "1Ô∏è‚É£",
	2:  "2Ô∏è‚É£",
	3:  "3Ô∏è‚É£",
	4:  "4Ô∏è‚É£",
	5:  "5Ô∏è‚É£",
	6:  "6Ô∏è‚É£",
	7:  "7Ô∏è‚É£",
	8:  "8Ô∏è‚É£",
	9:  "9Ô∏è‚É£",
	10: "üîü",
}

// On Windows I get a *fs.PathError calling zap.L().Sync() to flush logger on shutdown.
// This just calls zap.L().Sync() and ignores that specific error. See https://github.com/uber-go/zap/issues/991
func SyncLogger() error {
	var pathErr *fs.PathError
	if err := zap.L().Sync(); err != nil && !errors.As(err, &pathErr) {
		return fmt.Errorf("error syncing logger: %w", err)
	}
	return nil
}
